### ISSUE TITLE
webviz_fan_chart datetime index

### ISSUE THREAD

**Issue by fahaddilib** [Statoil/webviz#52]
![image](https://user-images.githubusercontent.com/34888303/44854652-6cb2c980-ac69-11e8-871e-90fe56c0ceed.png)

Attempted to use the FanChart for the above DataFrame where the index is a datetime object, but the following typeError message was thrown:

![image](https://user-images.githubusercontent.com/34888303/44855098-9c160600-ac6a-11e8-8eb0-fd8d16172f1b.png)

**Comment by anders-kiaer** [comment]
Related to #46 perhaps (where check for `pd.core.indexes.datetimes.DatetimeIndex` was added). Should in addition check for `datetime.date` and `datetime.datetime`?

**Comment by fortena** [comment]
#66 support added here
