### ISSUE TITLE
History matching

### ISSUE THREAD

**Issue by sivhollup** [Statoil/webviz#55]
This deals with porting history matching from webportal to webviz. 

- [ ] Specify functionality (what should be done this round, what remains later on?
- [ ] Port functionality from webportal

**Comment by anders-kiaer** [comment]
Closing this as of now. Focus for `webviz` core team should be on adding core functionality. Meanwhile, specialized "_petech_ plots" (except `Map`) will be matured in terms of features (and integration with data sources) in https://github.com/Statoil/webviz_petech.
