### ISSUE TITLE
Plotly plots does not resize

### ISSUE THREAD

**Issue by anders-kiaer** [Statoil/webviz#76]
Plotly based visualizations currently does not resize.

**Comment by kristofferlund** [comment]
Been investigating this one, but I can not get it to work with with our examples https://codepen.io/plotly/pen/BOxMXz

**Comment by anders-kiaer** [comment]
You probably have done it correct @kristofferlund, but using a too old version of plotly. The `responsive` option to `config` is only a few days old (see https://github.com/plotly/plotly.js/pull/2974 and changelog of https://github.com/plotly/plotly.js/releases/tag/v1.41.0).
